var song_titles = [
  'Pretty Liar (M@STER VERSION)',
  'フェスタ・イルミネーション',
  'スタートリップ',
  'メルヘン∞メタモルフォーゼ!',
  'DETECTIVE HIGH! ～恋探偵物語～',
  '空想文学少女',
  'きらりんロボのテーマ',
  'SUPER SIZE LOVE!!',
  'おかしな国のおかし屋さん',
  'Day After "Yesterday"',
  'HARURUNRUN',
  'Frost',
  'お願い！シンデレラ',
  '風色メロディ',
  'にょわにょわーるど☆',
  'CoCo夏夏夏 Holiday',
  'ラジオ体操第二',
  'ハピリリ',
  'piece of cake',
  'はなしらべ',
  'Love∞Destiny (M@STER VERSION)',
  'Marionetteは眠らない',
  '恋心マスカレード',
  'Neo Beautiful Pain',
  'shiny smile (M@STER VERSION)',
  'Catch my dream',
  'Believe my change!',
  'Wonder goes on!!',
  'ToP!!!!!!!!!!!!! (M@STER VERSION)',
  'Happy x 2 Days',
  '心もよう',
  'G F',
  '∀NSWER (M@STER VERSION)',
  'With Love (M@STER VERSION)',
  'こいかぜ',
  'キラッ!満開スマイル',
  'お願い! シンデレラ -しんげきRemix-',
  'Nothing but You (M@STER VERSION)',
  'ブルウ・スタア',
  'The world is all one!! (M@STER VERSION)',
  'ハルカナミライ',
  'Miracle Night (M@STER VERSION)',
  'ファンタジスタ・カーニバル',
  'Rockin\' Emotion',
  'サマカニ!! (M@STER VERSION)',
  'Sister',
  'アップルパイ・プリンセス',
  'カワラナイモノ',
  '団結2010',
  '華蕾夢ミル狂詩曲～魂ノ導～',
  '幻惑SILHOUETTE',
  'STANDING ALIVE',
  'Understand?Understand!',
  '恋愛ロードランナー',
  'アマテラス (M@STER VERSION)',
  'i',
  'できたてEvo! Revo! Generation!',
  'Stage bye Stage',
  '創造は始まりの風を連れて',
  'チョー↑元気Show☆アイドルch@ng!',
  '夜空に輝く星座のように',
  'モーレツ★世直しギルティ! (M@STER VERSION)',
  'あんきら！？狂騒曲 (M@STER VERSION)',
  'プリンセス・アラモード',
  'White again',
  'タイムマシンに飛び乗って!',
  'Tulip (M@STER VERSION)',
  'GOIN\'!!!',
  'Growing Storm!',
  'fuity love',
  'Bloody Festa',
  'Heart・デイズ・Night☆',
  '夏恋 -NATSU KOI-',
  'M@GIC☆',
  'スマイルいちばん',
  'ステップ！',
  'あのね、聞いてほしいことがあるんだ',
  'cherry＊merry＊cherry',
  '夕映えプレゼント　–凸レーションリミックス-',
  'Get My Shinin\'',
  'ジレるハートに火をつけて',
  '秋風に手を振って',
  'フレデリカ、猫やめるよ',
  'りんごのマーチ',
  '流星PARADE',
  'ふわりずむ',
  'Twilight Sky',
  '情熱ファンファンファーレ (M@STER VERSION)',
  'UNION!!',
  'たんけんぼうけん☆ハイホー隊',
  'bitter sweet',
  'ローリング△さんかく',
  'Spring Screaming',
  'NO CURRY NO LIFE',
  'ZETTAI x BREAK!! トゥインクルリズム',
  'PROUST EFFECT',
  'Helloコンチェルト',
  'Bright Blue',
  '夢色トレイン',
  'Light Year Song',
  'あんずのうた',
  '薄荷 -ハッカ-',
  '秘密のメモリーズ',
  'みなぎれ! ボボボンバー',
  'Take me☆Take you',
  'SUPERLOVE☆',
  'Snow*Love',
  'Decided',
  '僕たちのResistance (M@STER VERSION)',
  'S(mile)ING! -LIVE MIX-',
  '嘆きのFRACTION',
  'ススメ☆オトメ ～jewel parade～',
  'Dreaming of you',
  'はにかみdays',
  '合言葉はスタートアップ!',
  '未来系ドリーマー',
  'ゴキゲンParty Night',
  'ランニング・ハイッ',
  'Trancing Pulse',
  'dear...',
  'EVERMORE (M@STER VERSION)',
  'Blooming Days',
  'MUSIC♪ (M@STER VERSION)',
  'HELLO, YOUR ANGEL♪',
  'たくさん!',
  'Reason!!',
  'スポーツ! スポーツ! スポーツ!',
  'プラリネ',
  'Colorful Days (M@STER VERSION)',
  'Funny Logic',
  'ラブレター (M@STER VERSION)',
  '青の一番星',
  '空',
  '踊りまくろ☆ダンシング・ナイト',
  'インセインゲーム',
  'Only One Second',
  '水中キャンディ',
  'Persona Voice',
  'CHANGE!!!! (M@STER VERSION)',
  'LET\'S GO HAPPY!!',
  'ドリームトラベラー',
  'little trip around the world',
  'リトルリドル (M@STER VERSION)',
  'ハッピ～ エフェクト!',
  '輝く世界の魔法 (NEW GENERATIONS VERSION)',
  'ジャングル☆パーティー',
  '満腹至極フルコォス',
  'WORLD WIDE DANCE!!!',
  '恋のHamburg♪',
  'リフレインキス',
  '素敵なキセキ',
  'Eternal Harmony',
  'さよならアンドロメダ',
  '...In The Name Of。...LOVE?',
  'Legend Girls!!',
  '毒茸伝説',
  'ぴにゃこら太絵かき歌',
  'アニマル☆ステイション!',
  'Dreaming!',
  'SUN♡FLOWER',
  'あめにうたおう♪',
  '輝く世界の魔法 (M@STER VERSION)',
  'Melody in scape',
  'ラジオ体操第一',
  '秘密のトワレ',
  '流れ星キセキ',
  '輝く世界の魔法 -しんげきRemix-',
  'き・ま・ぐ・れ☆Cafe au lait!',
  'カーニヴァル・ジャパネスク',
  '私色ギフト',
  'きみにいっぱい☆',
  '2nd SIDE',
  'Good-Sleep, Baby',
  '初恋バタフライ',
  'READY!! (M@STER VERSION)',
  'Jet to the Future (M@STER VERSION)',
  'ヴィーナスシンドローム',
  'ラヴィアンローズ',
  'ØωØver!!',
  'サマ☆トリ ～Summer trip～',
  'if',
  'みんなのきもち',
  'Romantic Now',
  'ライアー・ルージュ',
  'ハピガ!',
  'ココロがかえる場所',
  'Take! 3.2.1.→S・P・A・C・E↑↑',
  '鳥籠スクリプチュア',
  'Last Kiss',
  'Everlasting',
  'たしかな足跡',
  'Frozen Tears',
  'Tomorrow Program',
  'Eternal Spiral',
  'ホントウノワタシ',
  '恋の音色ライン',
  '地球ミラーボウル',
  'BRAVE STAR',
  '飛べない鳥は夜に鳴く',
  'ココロ☆エクササイズ',
  '恋色エナジー',
  'Absolute NIne',
  'あいくるしい',
  'オリジナル声になって',
  'エヴリデイドリーム',
  'in fact',
  'グッデイ・サンシャイン!',
  'HOME RUN SONG♪',
  '君だけの欠片',
  '聖炎の女神',
  '侠気乱舞',
  'Memories',
  'Be My Boy',
  'CAT CROSSING',
  'GREEDY GIRL',
  '流星群',
  'Come on a Tea Party!',
  'Shine!!',
  'Star!!',
  'GO MY WAY!! (M@STER VERSION)',
  'トキメキの音符になって',
  '永遠の花',
  'Rebellion',
  'つぼみ',
  'デコレーション・ドリ～ミンッ♪',
  'メッセージ -しんげきRemix-',
  '花簪 HANAKANZASHI',
  '君への詩',
  'ときどきシーソー',
  'ハミングバード',
  'メッセージ',
  '生存本能ヴァルキュリア (M@STER VERSION)',
  '瞳の中のシリウス',
  'キミがいて夢になる',
  '熱血乙女A',
  'でれぱ音頭',
  'Bonnes! Bonnes!! Vacances!!!',
  'ちいさな恋の足音',
  '待ちぼうけのLacrima',
  'Emergence　Vibe',
  '恋花',
  'シャクネツのパレード',
  'Impervious Resolution',
  'Precious Grain',
  'Silent Joker',
  'Dreamscape',
  'キミのそばでずっと',
  'S(mile)ING!',
  'Beat the World!!',
  'WE ARE ONE!!',
  'PANDEMIC ALONE',
  'AIKANE?',
  '気持ちいいよね 一等賞！',
  'ヒカリのdestination',
  'WHY?',
  'ミツボシ☆☆★',
  'Thank You!',
  'Sweet Sweet Soul',
  'プライヴェイト・ロードショウ (playback, Weekday)',
  '夢咲きAfter school',
  '未来飛行',
  'Dear My Dreamers',
  'Super Lover',
  '追憶のサンドグラス',
  'メメント? モメント♪ ルルルルル☆',
  'Hotel Moonside(Extended Live Version)',
  'とどけ! アイドル',
  '微笑んだから、気づいたんだ。',
  'ムーンゴールド',
  'スノウレター',
  'Hearty!!',
  '深層マーメイド',
  'インヴィンシブル・ジャスティス',
  '求ム VS マイ・フューチャー',
  'Can\'t Stop!!',
  'ハートウォーミング',
  'シルエット',
  'この空の下',
  'addicted',
  '赤い世界が消える頃',
  'エスケープ',
  'Voyage',
  '成長Chu→LOVER!!',
  'プリムラ',
  '月のほとりで',
  'Fu-Wa-Du-Wa',
  'ススメ☆オトメ ～jewel parade～ -しんげきRemix-',
  'lilac time',
  '自分REST@RT (M@STER VERSION)',
  '純情Midnight伝説 (M@STER VERSION)',
  '銀のイルカと熱い風',
  '絵本',
  'メルヘンデビュー!',
  '薄紅',
  'EVERMORE -しんげきRemix-',
  'Treasure☆ (M@STER VERSION)',
  '楽園',
  'ゲキテキ! ムテキ! 恋したい!',
  'マイ・スイート・ハネムーン',
  'Kawaii make MY day! (M@STER VERSION)',
  'アライブファクター',
  'DIAMOND DAYS',
  'Bigバルーン◎',
  'わたぐも',
  '夕風のメロディー',
  'Princess Be Ambitious!!',
  'TOKIMEKIエスカレート',
  'Maria Trap',
  '小さな恋の密室事件',
  'Sentimental Venus',
  'とどけ! アイドル -しんげきRemix-',
  'One Life',
  '祈りの花',
  '共鳴世界の存在論',
  '空に手が触れる場所',
  '夕映えプレゼント　-＊(Asterisk)リミックス-',
  'SING MY SONG',
  '咲いてJewel',
  'Heart Voice',
  'STEREOPHONIC ISOTONIC',
  'ストロベリー･キューピッド',
  'Blue Symphony',
  'Oli Oli DISCO',
  'FLY TO EVERYWHERE',
  'SMOKY FRUITS',
  'Trust me',
  'VIVID イマジネーション',
  'BOUNCING♪ SMILE!',
  'ユニゾン☆ビート',
  '地球儀にない国',
  '瑠璃色金魚と花菖蒲',
  'POKER POKER',
  'Blooming Star (M@STER VERSION)',
  'BEYOND THE STARLIGHT (M@STER VERSION)',
  'Up! 10sion♪Pleeeeeeeeease!',
  '絶対特権主張しますっ!',
  'IMPRESSION→LOCOMOTION!',
  'always',
  'Border LINE→→→',
  'L・O・B・M',
  'ツインテールの風',
  'Dreaming Star',
  '想い出はクリアスカイ',
  'To my darling...',
  '微笑み日和',
  'サイキック! ぱーりーないと☆',
  'Liar\'s good bye',
  'To...',
  'フローズン・ワード',
  'AnemoneStar',
  '"Your" HOME TOWN',
  'Welcome!!',
  'Smiling Crescent',
  'Happy Darling',
  'アツアツ♪マカロニグラタン',
  'PRETTY DREAMER',
  'Raise the FLAG',
  'いとしーさー',
  '教えてlast note...',
  'NUDIE★',
  'おんなの道は星の道',
  '追い風Running',
  '虹になれ',
  'ミラクルテレパシー',
  'vivid color',
  'Birth of Color',
  'FairyTaleじゃいられない',
  'Multicolored Sky',
  'Flip Flop',
  'アルストロメリア',
  'エンジェル ドリーム ～CINDERELLA GIRLS COLLABORATION MIX～',
  '私たちはずっと…でしょう',
  'お散歩カメラ',
  'ロケットスター☆',
  'バベルシティ・グレイス',
  'Shooting Stars',
  'FIND YOUR WIND!',
  'おまじない',
  'ホップ♪ステップ♪レインボウ♪',
  'Orange Sapphire',
  'Spread the Wings!!',
  '恋が咲く季節',
  '昏き星、遠い月',
  '恋のLesson初級編',
  'MY STYLE! OUR STYLE!!!!',
  'Halloween Code',
  'ニャンと☆スペクタクル',
  '双翼の独奏歌 (M@STER VERSION)',
  'smiley days',
  'You\'re stars shine on me',
  '想いはCarnaval',
  'Cut. Cut. Cut.',
  '桜の風',
  '君想いBirthday',
  'Radio Happy',
  '虹色letters',
  '透明なプロローグ',
  'DOKIDOKIリズム',
  'Flip Flop ～For SS3A rearrange Mix～',
  '空想探査計画',
  'マイペース☆マイウェイ',
  'プリティ～～～ッ→ニャンニャンッ!',
  '朝焼けのクレッシェンド',
  'We\'re the friends!',
  'Near to You',
  '未完成の歴史',
  'Snow White',
  'オルゴールの小箱',
  '夢色ハーモニー',
  'オレンジの空の下',
  'ENTER→PLEASURE',
  'Starry-Go-Round (M@STER VERSION)',
  'Naked Romance',
  'ハミングロード',
  'CRIMSON LOVERS',
  'P.S I Love You',
  'アタシポンコツアンドロイド',
  'OωOver!! -Heart Beat Version-',
  '"HELLO!!" (M@STER VERSION)',
  'ハッピー☆ラッキー☆ジェットマシーン',
  'shabon song',
  '銀河図書館',
  '太陽キッス',
  'Brand New Theater!',
  'Melty Fantasia',
  '夕映えプレゼント -new generationsリミックス-',
  '祈りの羽根',
  'MEGARE! (M@STER VERSION)',
  'Sparkling Girl',
  'Private Sign',
  'スローライフ・ファンタジー',
  'ましゅまろ☆キッス',
  'おねだり Shall We～?',
  'エチュードは1曲だけ',
  'Nocturne',
  'Hotel Moonside',
  'FAKE SELF x TRUE SELF',
  '青空リレーション',
  'HOME, SWEET FRIENDSHIP',
  'Angelic Parade♪',
  'ビギナーズ☆ストライク',
  'Nebula Sky',
  'Lunatic Show',
  'Home is a coming now!',
  'とんでいっちゃいたいの',
  '星屑のシンフォニア',
  'WOW! I NEED!! ～シンギングモンキー 歌唱拳～',
  '空と風と恋のワルツ',
  'アフタースクールパーリータイム',
  'Angel Breeze',
  'Nation Blue',
  '冬空プレシャス',
  'ART NEEDS HEART BEATS',
];

var song_files = [
  'audio/01 Pretty Liar (M@STER VERSION).mp3',
  'audio/1-03 フェスタ・イルミネーション.mp3',
  'audio/05 スタートリップ.mp3',
  'audio/1-02 メルヘン∞メタモルフォーゼ!.mp3',
  'audio/1-09 DETECTIVE HIGH! ～恋探偵物語～.mp3',
  'audio/1-04 空想文学少女 1.mp3',
  'audio/08 きらりんロボのテーマ.mp3',
  'audio/1-02 SUPER SIZE LOVE!!.mp3',
  'audio/02 おかしな国のおかし屋さん.mp3',
  'audio/1-04 Day After _Yesterday_.mp3',
  'audio/1-02 HARURUNRUN 1.mp3',
  'audio/1-03 Frost.mp3',
  'audio/02 お願い！シンデレラ.mp3',
  'audio/01 風色メロディ.mp3',
  'audio/02 にょわにょわーるど☆.mp3',
  'audio/1-04 CoCo夏夏夏 Holiday.mp3',
  'audio/1-08 ラジオ体操第二.mp3',
  'audio/1-02 ハピリリ.mp3',
  'audio/08 piece of cake.mp3',
  'audio/1-05 はなしらべ.mp3',
  'audio/01 Love∞Destiny (M@STER VERSION).mp3',
  'audio/1-11 Marionetteは眠らない.mp3',
  'audio/1-05 恋心マスカレード.mp3',
  'audio/02 Neo Beautiful Pain.mp3',
  'audio/1-05 shiny smile (M@STER VERSION).mp3',
  'audio/1-06 Catch my dream.mp3',
  'audio/1-05 Believe my change!.mp3',
  'audio/1-01 Wonder goes on!!.mp3',
  'audio/1-01 ToP!!!!!!!!!!!!! (M@STER VERSION).mp3',
  'audio/1-01 Happy x 2 Days.mp3',
  'audio/1-02 心もよう.mp3',
  'audio/1-06 G F.mp3',
  'audio/1-01 ∀NSWER (M@STER VERSION).mp3',
  'audio/1-01 With Love (M@STER VERSION).mp3',
  'audio/01 こいかぜ.mp3',
  'audio/1-01 キラッ!満開スマイル.mp3',
  'audio/1-08 お願い! シンデレラ -しんげきRemix-.mp3',
  'audio/1-01 Nothing but You (M@STER VERSION).mp3',
  'audio/1-03 ブルウ・スタア 1.mp3',
  'audio/1-10 The world is all one!! (M@STER VERSION).mp3',
  'audio/04 ハルカナミライ.mp3',
  'audio/1-01 Miracle Night (M@STER VERSION).mp3',
  'audio/1-02 ファンタジスタ・カーニバル.mp3',
  'audio/1-02 Rockin\' Emotion.mp3',
  'audio/01 サマカニ!! (M@STER VERSION).mp3',
  'audio/03 Sister.mp3',
  'audio/01 アップルパイ・プリンセス.mp3',
  'audio/1-11 カワラナイモノ.mp3',
  'audio/1-16 団結2010.mp3',
  'audio/01 華蕾夢ミル狂詩曲～魂ノ導～ 1.mp3',
  'audio/1-02 幻惑SILHOUETTE.mp3',
  'audio/1-01 STANDING ALIVE.mp3',
  'audio/1-04 Understand_Understand!.mp3',
  'audio/1-02 恋愛ロードランナー.mp3',
  'audio/1-01 アマテラス (M@STER VERSION).mp3',
  'audio/1-03 i.mp3',
  'audio/01 できたてEvo! Revo! Generation!.mp3',
  'audio/1-01 Stage bye Stage.mp3',
  'audio/1-01 創造は始まりの風を連れて.mp3',
  'audio/1-09 チョー↑元気Show☆アイドルch@ng!.mp3',
  'audio/1-07 夜空に輝く星座のように.mp3',
  'audio/1-01 モーレツ★世直しギルティ! (M@STER VERSION).mp3',
  'audio/01 あんきら！？狂騒曲 (M@STER VERSION).mp3',
  'audio/1-01 プリンセス・アラモード 1.mp3',
  'audio/1-02 White again.mp3',
  'audio/1-05 タイムマシンに飛び乗って!.mp3',
  'audio/01 Tulip (M@STER VERSION).mp3',
  'audio/1-02 GOIN\'!!!.mp3',
  'audio/1-01 Growing Storm!.mp3',
  'audio/1-05 fuity love.mp3',
  'audio/03 Bloody Festa.mp3',
  'audio/1-03 Heart・デイズ・Night☆ 1.mp3',
  'audio/1-03 夏恋 -NATSU KOI-.mp3',
  'audio/1-01 M@GIC☆.mp3',
  'audio/1-05 スマイルいちばん.mp3',
  'audio/02 ステップ！.mp3',
  'audio/1-07 あのね、聞いてほしいことがあるんだ.mp3',
  'audio/03 cherry＊merry＊cherry.mp3',
  'audio/02 夕映えプレゼント　–凸レーションリミックス-.mp3',
  'audio/1-05 Get My Shinin\'.mp3',
  'audio/1-01 ジレるハートに火をつけて.mp3',
  'audio/1-01 秋風に手を振って 1.mp3',
  'audio/1-02 フレデリカ、猫やめるよ 1.mp3',
  'audio/1-04 りんごのマーチ.mp3',
  'audio/1-02 流星PARADE 1.mp3',
  'audio/1-02 ふわりずむ 1.mp3',
  'audio/01 Twilight Sky.mp3',
  'audio/1-01 情熱ファンファンファーレ (M@STER VERSION).mp3',
  'audio/1-01 UNION!!.mp3',
  'audio/1-03 たんけんぼうけん☆ハイホー隊.mp3',
  'audio/1-04 bitter sweet.mp3',
  'audio/1-01 ローリング△さんかく.mp3',
  'audio/1-04 Spring Screaming.mp3',
  'audio/1-08 NO CURRY NO LIFE.mp3',
  'audio/1-02 ZETTAI x BREAK!! トゥインクルリズム.mp3',
  'audio/1-03 PROUST EFFECT.mp3',
  'audio/1-03 Helloコンチェルト 1.mp3',
  'audio/01 Bright Blue.mp3',
  'audio/1-02 夢色トレイン.mp3',
  'audio/1-01 Light Year Song.mp3',
  'audio/01 あんずのうた.mp3',
  'audio/01 薄荷 -ハッカ- 1.mp3',
  'audio/1-08 秘密のメモリーズ 1.mp3',
  'audio/1-02 みなぎれ! ボボボンバー.mp3',
  'audio/01 Take me☆Take you.mp3',
  'audio/1-02 SUPERLOVE☆.mp3',
  'audio/1-01 Snow_Love.mp3',
  'audio/1-08 Decided.mp3',
  'audio/1-01 僕たちのResistance (M@STER VERSION).mp3',
  'audio/1-03 S(mile)ING! -LIVE MIX-.mp3',
  'audio/1-09 嘆きのFRACTION.mp3',
  'audio/1-07 ススメ☆オトメ ～jewel parade～.mp3',
  'audio/1-02 Dreaming of you.mp3',
  'audio/1-02 はにかみdays.mp3',
  'audio/1-01 合言葉はスタートアップ!.mp3',
  'audio/1-05 未来系ドリーマー 1.mp3',
  'audio/1-07 ゴキゲンParty Night.mp3',
  'audio/1-02 ランニング・ハイッ.mp3',
  'audio/1-01 Trancing Pulse.mp3',
  'audio/1-07 dear....mp3',
  'audio/1-01 EVERMORE (M@STER VERSION).mp3',
  'audio/1-01 Blooming Days.mp3',
  'audio/1-15 MUSIC♪ (M@STER VERSION).mp3',
  'audio/1-05 HELLO, YOUR ANGEL♪ 1.mp3',
  'audio/1-02 たくさん!.mp3',
  'audio/1-01 Reason!!.mp3',
  'audio/1-02 スポーツ! スポーツ! スポーツ!.mp3',
  'audio/1-03 プラリネ.mp3',
  'audio/1-06 Colorful Days (M@STER VERSION).mp3',
  'audio/1-02 Funny Logic.mp3',
  'audio/1-01 ラブレター (M@STER VERSION).mp3',
  'audio/01 青の一番星.mp3',
  'audio/1-04 空 1.mp3',
  'audio/1-03 踊りまくろ☆ダンシング・ナイト 1.mp3',
  'audio/1-05 インセインゲーム.mp3',
  'audio/1-03 Only One Second.mp3',
  'audio/1-06 水中キャンディ 1.mp3',
  'audio/1-05 Persona Voice.mp3',
  'audio/1-12 CHANGE!!!! (M@STER VERSION).mp3',
  'audio/01 LET\'S GO HAPPY!!.mp3',
  'audio/1-01 ドリームトラベラー.mp3',
  'audio/1-07 little trip around the world.mp3',
  'audio/1-01 リトルリドル (M@STER VERSION).mp3',
  'audio/1-07 ハッピ～ エフェクト!.mp3',
  'audio/03 輝く世界の魔法 (NEW GENERATIONS VERSION).mp3',
  'audio/1-05 ジャングル☆パーティー.mp3',
  'audio/1-02 満腹至極フルコォス 1.mp3',
  'audio/1-02 WORLD WIDE DANCE!!!.mp3',
  'audio/01 恋のHamburg♪.mp3',
  'audio/1-02 リフレインキス.mp3',
  'audio/1-02 素敵なキセキ 1.mp3',
  'audio/1-01 Eternal Harmony.mp3',
  'audio/1-03 さよならアンドロメダ.mp3',
  'audio/1-02 ...In The Name Of。...LOVE_.mp3',
  'audio/1-12 Legend Girls!!.mp3',
  'audio/01 毒茸伝説 1.mp3',
  'audio/1-08 ぴにゃこら太絵かき歌.mp3',
  'audio/1-03 アニマル☆ステイション!.mp3',
  'audio/1-01 Dreaming!.mp3',
  'audio/01 SUN♡FLOWER.mp3',
  'audio/1-05 あめにうたおう♪.mp3',
  'audio/01 輝く世界の魔法 (M@STER VERSION) 1.mp3',
  'audio/1-08 Melody in scape.mp3',
  'audio/1-08 ラジオ体操第一.mp3',
  'audio/01 秘密のトワレ 1.mp3',
  'audio/1-01 流れ星キセキ 1.mp3',
  'audio/1-08 輝く世界の魔法 -しんげきRemix- 1.mp3',
  'audio/01 き・ま・ぐ・れ☆Cafe au lait! 1.mp3',
  'audio/1-02 カーニヴァル・ジャパネスク.mp3',
  'audio/1-01 私色ギフト 1.mp3',
  'audio/1-01 きみにいっぱい☆ 1.mp3',
  'audio/01 2nd SIDE.mp3',
  'audio/1-11 Good-Sleep, Baby.mp3',
  'audio/1-04 初恋バタフライ.mp3',
  'audio/1-11 READY!! (M@STER VERSION).mp3',
  'audio/1-01 Jet to the Future (M@STER VERSION).mp3',
  'audio/01 ヴィーナスシンドローム.mp3',
  'audio/01 ラヴィアンローズ.mp3',
  'audio/01 ØωØver!!.mp3',
  'audio/1-03 サマ☆トリ ～Summer trip～.mp3',
  'audio/1-02 if.mp3',
  'audio/01 みんなのきもち.mp3',
  'audio/01 Romantic Now.mp3',
  'audio/1-07 ライアー・ルージュ.mp3',
  'audio/1-02 ハピガ!.mp3',
  'audio/1-11 ココロがかえる場所.mp3',
  'audio/1-01 Take! 3.2.1.→S・P・A・C・E↑↑.mp3',
  'audio/1-05 鳥籠スクリプチュア.mp3',
  'audio/1-01 Last Kiss.mp3',
  'audio/2-02 Everlasting.mp3',
  'audio/1-09 たしかな足跡.mp3',
  'audio/1-03 Frozen Tears.mp3',
  'audio/1-06 Tomorrow Program.mp3',
  'audio/07 Eternal Spiral.mp3',
  'audio/1-06 ホントウノワタシ 1.mp3',
  'audio/1-03 恋の音色ライン.mp3',
  'audio/1-02 地球ミラーボウル.mp3',
  'audio/1-01 BRAVE STAR.mp3',
  'audio/1-05 飛べない鳥は夜に鳴く.mp3',
  'audio/1-05 ココロ☆エクササイズ.mp3',
  'audio/01 恋色エナジー.mp3',
  'audio/1-01 Absolute NIne 1.mp3',
  'audio/03 あいくるしい.mp3',
  'audio/1-07 オリジナル声になって.mp3',
  'audio/01 エヴリデイドリーム.mp3',
  'audio/01 in fact.mp3',
  'audio/1-05 グッデイ・サンシャイン!.mp3',
  'audio/1-02 HOME RUN SONG♪ 1.mp3',
  'audio/1-05 君だけの欠片.mp3',
  'audio/1-03 聖炎の女神 1.mp3',
  'audio/1-01 侠気乱舞.mp3',
  'audio/1-06 Memories.mp3',
  'audio/1-07 Be My Boy.mp3',
  'audio/1-04 CAT CROSSING.mp3',
  'audio/1-11 GREEDY GIRL.mp3',
  'audio/1-09 流星群 1.mp3',
  'audio/1-01 Come on a Tea Party!.mp3',
  'audio/1-01 Shine!!.mp3',
  'audio/01 Star!!.mp3',
  'audio/1-02 GO MY WAY!! (M@STER VERSION).mp3',
  'audio/1-06 トキメキの音符になって.mp3',
  'audio/1-08 永遠の花 1.mp3',
  'audio/1-10 Rebellion.mp3',
  'audio/1-02 つぼみ.mp3',
  'audio/1-09 デコレーション・ドリ～ミンッ♪.mp3',
  'audio/1-09 メッセージ -しんげきRemix-.mp3',
  'audio/01 花簪 HANAKANZASHI 1.mp3',
  'audio/1-02 君への詩.mp3',
  'audio/1-02 ときどきシーソー.mp3',
  'audio/1-05 ハミングバード 1.mp3',
  'audio/02 メッセージ.mp3',
  'audio/01 生存本能ヴァルキュリア (M@STER VERSION) 1.mp3',
  'audio/1-11 瞳の中のシリウス 1.mp3',
  'audio/1-06 キミがいて夢になる 1.mp3',
  'audio/01 熱血乙女A 1.mp3',
  'audio/1-02 でれぱ音頭.mp3',
  'audio/1-06 Bonnes! Bonnes!! Vacances!!!.mp3',
  'audio/1-07 ちいさな恋の足音.mp3',
  'audio/1-08 待ちぼうけのLacrima.mp3',
  'audio/1-07 Emergence　Vibe.mp3',
  'audio/1-09 恋花.mp3',
  'audio/01 シャクネツのパレード.mp3',
  'audio/1-05 Impervious Resolution.mp3',
  'audio/1-10 Precious Grain.mp3',
  'audio/1-04 Silent Joker.mp3',
  'audio/1-08 Dreamscape.mp3',
  'audio/02 キミのそばでずっと.mp3',
  'audio/01 S(mile)ING!.mp3',
  'audio/1-06 Beat the World!!.mp3',
  'audio/01 WE ARE ONE!!.mp3',
  'audio/03 PANDEMIC ALONE.mp3',
  'audio/1-01 AIKANE_.mp3',
  'audio/01 気持ちいいよね 一等賞！ 1.mp3',
  'audio/1-01 ヒカリのdestination.mp3',
  'audio/1-03 WHY_.mp3',
  'audio/01 ミツボシ☆☆★.mp3',
  'audio/01 Thank You!.mp3',
  'audio/1-04 Sweet Sweet Soul.mp3',
  'audio/1-09 プライヴェイト・ロードショウ (playback, Weekday).mp3',
  'audio/1-01 夢咲きAfter school.mp3',
  'audio/1-06 未来飛行 1.mp3',
  'audio/1-02 Dear My Dreamers.mp3',
  'audio/1-03 Super Lover.mp3',
  'audio/1-07 追憶のサンドグラス.mp3',
  'audio/1-06 メメント_ モメント♪ ルルルルル☆.mp3',
  'audio/01 Hotel Moonside(Extended Live Version).mp3',
  'audio/1-02 とどけ! アイドル.mp3',
  'audio/1-05 微笑んだから、気づいたんだ。.mp3',
  'audio/04 ムーンゴールド.mp3',
  'audio/1-03 スノウレター.mp3',
  'audio/1-05 Hearty!! 1.mp3',
  'audio/1-04 深層マーメイド 1.mp3',
  'audio/1-03 インヴィンシブル・ジャスティス.mp3',
  'audio/1-04 求ム VS マイ・フューチャー 1.mp3',
  'audio/01 Can\'t Stop!!.mp3',
  'audio/1-09 ハートウォーミング.mp3',
  'audio/04 シルエット.mp3',
  'audio/1-01 この空の下.mp3',
  'audio/1-05 addicted.mp3',
  'audio/1-01 赤い世界が消える頃 1.mp3',
  'audio/06 エスケープ.mp3',
  'audio/1-03 Voyage.mp3',
  'audio/05 成長Chu→LOVER!!.mp3',
  'audio/1-06 プリムラ 1.mp3',
  'audio/1-04 月のほとりで.mp3',
  'audio/1-11 Fu-Wa-Du-Wa.mp3',
  'audio/1-09 ススメ☆オトメ ～jewel parade～ -しんげきRemix-.mp3',
  'audio/01 lilac time.mp3',
  'audio/1-13 自分REST@RT (M@STER VERSION) 1.mp3',
  'audio/01 純情Midnight伝説 (M@STER VERSION) 1.mp3',
  'audio/1-01 銀のイルカと熱い風.mp3',
  'audio/1-05 絵本 1.mp3',
  'audio/01 メルヘンデビュー!.mp3',
  'audio/1-03 薄紅 1.mp3',
  'audio/1-09 EVERMORE -しんげきRemix-.mp3',
  'audio/1-01 Treasure☆ (M@STER VERSION).mp3',
  'audio/1-01 楽園 1.mp3',
  'audio/1-04 ゲキテキ! ムテキ! 恋したい!.mp3',
  'audio/1-02 マイ・スイート・ハネムーン 1.mp3',
  'audio/1-01 Kawaii make MY day! (M@STER VERSION).mp3',
  'audio/1-04 アライブファクター.mp3',
  'audio/1-06 DIAMOND DAYS.mp3',
  'audio/1-11 Bigバルーン◎.mp3',
  'audio/1-02 わたぐも.mp3',
  'audio/1-06 夕風のメロディー.mp3',
  'audio/1-01 Princess Be Ambitious!!.mp3',
  'audio/01 TOKIMEKIエスカレート.mp3',
  'audio/1-08 Maria Trap.mp3',
  'audio/01 小さな恋の密室事件.mp3',
  'audio/1-11 Sentimental Venus.mp3',
  'audio/1-08 とどけ! アイドル -しんげきRemix-.mp3',
  'audio/01 One Life.mp3',
  'audio/01 祈りの花 1.mp3',
  'audio/01 共鳴世界の存在論.mp3',
  'audio/02 空に手が触れる場所 1.mp3',
  'audio/02 夕映えプレゼント　-＊(Asterisk)リミックス-.mp3',
  'audio/1-05 SING MY SONG.mp3',
  'audio/1-01 咲いてJewel.mp3',
  'audio/1-02 Heart Voice 1.mp3',
  'audio/1-04 STEREOPHONIC ISOTONIC.mp3',
  'audio/1-03 ストロベリー･キューピッド.mp3',
  'audio/1-11 Blue Symphony.mp3',
  'audio/03 Oli Oli DISCO.mp3',
  'audio/1-07 FLY TO EVERYWHERE.mp3',
  'audio/1-05 SMOKY FRUITS 1.mp3',
  'audio/1-01 Trust me.mp3',
  'audio/1-03 VIVID イマジネーション.mp3',
  'audio/1-03 BOUNCING♪ SMILE!.mp3',
  'audio/1-03 ユニゾン☆ビート.mp3',
  'audio/1-02 地球儀にない国.mp3',
  'audio/1-04 瑠璃色金魚と花菖蒲 1.mp3',
  'audio/1-05 POKER POKER.mp3',
  'audio/1-02 Blooming Star (M@STER VERSION).mp3',
  'audio/1-01 BEYOND THE STARLIGHT (M@STER VERSION).mp3',
  'audio/1-05 Up! 10sion♪Pleeeeeeeeease!.mp3',
  'audio/1-01 絶対特権主張しますっ! 1.mp3',
  'audio/1-03 IMPRESSION→LOCOMOTION!.mp3',
  'audio/1-02 always.mp3',
  'audio/1-01 Border LINE→→→.mp3',
  'audio/1-07 L・O・B・M.mp3',
  'audio/1-01 ツインテールの風.mp3',
  'audio/1-08 Dreaming Star.mp3',
  'audio/1-06 想い出はクリアスカイ.mp3',
  'audio/01 To my darling....mp3',
  'audio/1-03 微笑み日和.mp3',
  'audio/1-02 サイキック! ぱーりーないと☆.mp3',
  'audio/1-04 Liar\'s good bye.mp3',
  'audio/1-04 To....mp3',
  'audio/1-05 フローズン・ワード 1.mp3',
  'audio/1-03 AnemoneStar.mp3',
  'audio/1-04 _Your_ HOME TOWN.mp3',
  'audio/1-02 Welcome!!.mp3',
  'audio/1-07 Smiling Crescent 1.mp3',
  'audio/1-06 Happy Darling.mp3',
  'audio/1-02 アツアツ♪マカロニグラタン.mp3',
  'audio/1-12 PRETTY DREAMER.mp3',
  'audio/1-02 Raise the FLAG.mp3',
  'audio/1-01 いとしーさー.mp3',
  'audio/1-04 教えてlast note....mp3',
  'audio/1-03 NUDIE★.mp3',
  'audio/1-01 おんなの道は星の道.mp3',
  'audio/01 追い風Running.mp3',
  'audio/1-02 虹になれ 1.mp3',
  'audio/01 ミラクルテレパシー.mp3',
  'audio/1-06 vivid color.mp3',
  'audio/1-01 Birth of Color.mp3',
  'audio/01 FairyTaleじゃいられない.mp3',
  'audio/1-02 Multicolored Sky.mp3',
  'audio/1-03 Flip Flop.mp3',
  'audio/1-01 アルストロメリア.mp3',
  'audio/1-05 エンジェル ドリーム ～CINDERELLA GIRLS COLLABORATION MIX～.mp3',
  'audio/1-14 私たちはずっと…でしょう 1.mp3',
  'audio/01 お散歩カメラ.mp3',
  'audio/1-03 ロケットスター☆.mp3',
  'audio/1-01 バベルシティ・グレイス.mp3',
  'audio/1-01 Shooting Stars.mp3',
  'audio/1-05 FIND YOUR WIND!.mp3',
  'audio/1-06 おまじない.mp3',
  'audio/1-03 ホップ♪ステップ♪レインボウ♪ 1.mp3',
  'audio/1-01 Orange Sapphire.mp3',
  'audio/1-01 Spread the Wings!!.mp3',
  'audio/1-01 恋が咲く季節.mp3',
  'audio/1-01 昏き星、遠い月.mp3',
  'audio/1-03 恋のLesson初級編.mp3',
  'audio/1-02 MY STYLE! OUR STYLE!!!!.mp3',
  'audio/1-02 Halloween Code.mp3',
  'audio/03 ニャンと☆スペクタクル.mp3',
  'audio/1-01 双翼の独奏歌 (M@STER VERSION).mp3',
  'audio/1-06 smiley days.mp3',
  'audio/01 You\'re stars shine on me.mp3',
  'audio/1-03 想いはCarnaval.mp3',
  'audio/1-06 Cut. Cut. Cut..mp3',
  'audio/1-01 桜の風 1.mp3',
  'audio/1-05 君想いBirthday.mp3',
  'audio/01 Radio Happy.mp3',
  'audio/1-02 虹色letters 1.mp3',
  'audio/1-04 透明なプロローグ.mp3',
  'audio/01 DOKIDOKIリズム.mp3',
  'audio/1-03 Flip Flop ～For SS3A rearrange Mix～.mp3',
  'audio/1-04 空想探査計画 1.mp3',
  'audio/1-03 マイペース☆マイウェイ 1.mp3',
  'audio/1-04 プリティ～～～ッ→ニャンニャンッ! 1.mp3',
  'audio/1-05 朝焼けのクレッシェンド.mp3',
  'audio/01 We\'re the friends!.mp3',
  'audio/1-07 Near to You.mp3',
  'audio/1-03 未完成の歴史.mp3',
  'audio/1-09 Snow White.mp3',
  'audio/1-01 オルゴールの小箱.mp3',
  'audio/1-02 夢色ハーモニー.mp3',
  'audio/1-08 オレンジの空の下.mp3',
  'audio/1-04 ENTER→PLEASURE.mp3',
  'audio/01 Starry-Go-Round (M@STER VERSION).mp3',
  'audio/01 Naked Romance.mp3',
  'audio/1-07 ハミングロード.mp3',
  'audio/1-02 CRIMSON LOVERS.mp3',
  'audio/1-04 P.S I Love You.mp3',
  'audio/1-03 アタシポンコツアンドロイド.mp3',
  'audio/1-02 OωOver!! -Heart Beat Version-.mp3',
  'audio/1-08 _HELLO!!_ (M@STER VERSION) 1.mp3',
  'audio/1-04 ハッピー☆ラッキー☆ジェットマシーン.mp3',
  'audio/1-03 shabon song.mp3',
  'audio/1-02 銀河図書館.mp3',
  'audio/1-02 太陽キッス.mp3',
  'audio/1-01 Brand New Theater!.mp3',
  'audio/01 Melty Fantasia.mp3',
  'audio/02 夕映えプレゼント -new generationsリミックス-.mp3',
  'audio/1-03 祈りの羽根 1.mp3',
  'audio/1-09 MEGARE! (M@STER VERSION).mp3',
  'audio/03 Sparkling Girl.mp3',
  'audio/1-03 Private Sign.mp3',
  'audio/1-02 スローライフ・ファンタジー.mp3',
  'audio/01 ましゅまろ☆キッス 1.mp3',
  'audio/01 おねだり Shall We～_.mp3',
  'audio/01 エチュードは1曲だけ.mp3',
  'audio/1-03 Nocturne.mp3',
  'audio/01 Hotel Moonside 1.mp3',
  'audio/1-02 FAKE SELF x TRUE SELF.mp3',
  'audio/02 青空リレーション.mp3',
  'audio/1-01 HOME, SWEET FRIENDSHIP 1.mp3',
  'audio/01 Angelic Parade♪.mp3',
  'audio/1-09 ビギナーズ☆ストライク.mp3',
  'audio/1-02 Nebula Sky.mp3',
  'audio/1-03 Lunatic Show.mp3',
  'audio/02 Home is a coming now! 1.mp3',
  'audio/1-02 とんでいっちゃいたいの.mp3',
  'audio/1-01 星屑のシンフォニア.mp3',
  'audio/1-05 WOW! I NEED!! ～シンギングモンキー 歌唱拳～.mp3',
  'audio/02 空と風と恋のワルツ 1.mp3',
  'audio/1-03 アフタースクールパーリータイム.mp3',
  'audio/01 Angel Breeze.mp3',
  'audio/1-01 Nation Blue.mp3',
  'audio/1-04 冬空プレシャス.mp3',
  'audio/1-03 ART NEEDS HEART BEATS.mp3',
];
